name: campuscash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  uuid: ^4.3.3
  velocity_x: ^4.1.2
  flutter_speed_dial: ^4.3.0
  syncfusion_flutter_charts: ^25.2.6
  syncfusion_flutter_datepicker: ^25.2.6
  table_calendar: ^3.0.9
  flutter_charts: ^0.5.2
  collection: ^1.18.0
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1




  dropdown_button2: ^2.0.0
  firebase_database: ^11.0.1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.1
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.0.5

  percent_indicator: ^4.2.3

  firebase_core: ^3.1.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  expense_repository:
    path: packages/expense_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image path: assets/CampusCashLogo.png
  adaptive_icon_foreground: assets/CampusCashLogo.png



flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
